### ISSUE TITLE
Handle Scrubbing (Touch)

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/embed#1]
At the moment if you go to https://wav.zbd.gg/track/75ba6880-cf73-4f26-9474-577d96627081 you can easily start and pause/stop the song from playing. But you cannot choose a specific part of the song to play by scrubbing left and right on the track like you can on apps such as spotify/youtube/apple music/etc.

This ticket is to handle this scrubbing feature on this module. This improved module should allow the user to drag the song play time location, and when it is unfocused/let-go, the song should quickly reload and then begin playing at that specific time in the song duration.

This iframe is only EVER rendered in a mobile environment so this needs to repsond really well to MOBILE TOUCH events. Please test accordingly.

**Comment by andrerfneves** [comment]
@andrerfneves to add info and submit for Algora

**Comment by andrerfneves** [comment]
Check `[trackId].tsx` file

**Comment by mnmt7** [comment]
/attempt #1

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cll0k05zu000al10f0j8jzor0/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by rishi-raj-jain** [comment]
@mnmt7 I already see you taking care of #3, can I pick this one? cc @andrerfneves

**Comment by andrerfneves** [comment]
@rishi-raj-jain you already have others to focus on for now. Let's leave this one for others. If @mnmt7 doesn't submit something in a timely manner we can discuss. Focus on the API Ref docs for now though

**Comment by rishi-raj-jain** [comment]
@andrerfneves Sounds good! Done with the API docs!

**Comment by andrerfneves** [comment]
Hey @mnmt7 seen that you have both #3 and #1 tickets, is it safe to say you're trying to claim them together? Any chance you can split the work with @rishi-raj-jain? Maybe one of you take one of the tickets each?

If you're already deep into it then that's okay, just want to give everyone a chance.

**Comment by andrerfneves** [comment]
Resolved by https://github.com/zebedeeio/wavlake-zbd-social-embed/pull/5
