### ISSUE TITLE
Show audioform behind scrubber

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/embed#3]
We want to add a soundform behind/above the player such that it renders similar to how it looks on soundcloud.com. Use a library/decoder/etc to understand the song and then provide the soundwave display. As the song plays, the displays gets `filled in` in the same way it does in Soundcloud.com.

<img width="910" alt="Screenshot 2023-08-07 at 12 13 11 AM" src="https://github.com/zebedeeio/wavlake-zbd-social-embed/assets/2574011/e1ca1521-786b-4d4a-9a94-9269cef2e51f">

**Comment by andrerfneves** [comment]
@andrerfneves to add info and submit for Algora

**Comment by mnmt7** [comment]
/attempt #3

<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cll0ka94y0002l00faun3zb31/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by andrerfneves** [comment]
hey @mnmt7 any updates on this ticket?

**Comment by kinston18** [comment]
/attempt #3


<details id="algora-options">
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cll0ka94y0002l00faun3zb31/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by andrerfneves** [comment]
@kinston18, @mnmt7 already submitted a PR completing the assignment, just FYI

**Comment by andrerfneves** [comment]
Resolved by https://github.com/zebedeeio/wavlake-zbd-social-embed/pull/5

**Comment by andrerfneves** [comment]
@mnmt7 i'm removing this bounty and putting the same $ from this bounty onto the other bounty since it's easier to do 1 payment only.
